server:
  port: 8081

spring:
  application:
    name: yonderapp
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/forecast
    username: gabidbr
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
